POST  http://localhost:5000/api/register
Content-Type: application/json

 {
  "name":"Tomas",
  "lastName":"Delgado ", 
  "identificationCard":1014180727,
  "userName":"Thomson",
  "email":"thomnson@gmail.com",
  "balance":0,
  "password":"sonic2"
}


 {
  "name":"Samuel",
  "lastName":" Monsalve", 
  "identificationCard":1014180728,
  "userName":"Somsom",
  "email":"samuelalejandro@gmail.com",
  "balance":0,
  "password":"Lukas2012"
}